version: '3.8'

services:
  # Backend service
  mcp-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8765:8765"
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8765
      - LOG_LEVEL=DEBUG
      - STATS_UPDATE_INTERVAL=2.0
      - CPU_ALERT_THRESHOLD=80.0
      - MEMORY_ALERT_THRESHOLD=90.0
      - DISK_ALERT_THRESHOLD=95.0
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    command: python main.py
    networks:
      - mcp-network
    restart: unless-stopped

  # Frontend service
  mcp-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_WS_URL=ws://localhost:8765
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./dashboard:/app/dashboard
      - /app/dashboard/node_modules
    working_dir: /app/dashboard
    command: npm start
    networks:
      - mcp-network
    depends_on:
      - mcp-backend
    stdin_open: true
    tty: true

networks:
  mcp-network:
    driver: bridge